name: 'terraform_state_artifact'
description: 'Sets up and runs Terraform, and creates an encrypted Terraform artifact'
author: 'Sturla Bragason'
inputs:
  folder:
    description: folder
    required: false
    default: 'sandbox'
  branch_name:
    description: branch
    required: false
    default: 'main'
  encryptionkey:
    description: 'Used to read artifact and as a key to encrypt and decrypt the state file artifact'
    required: true
  apply:
    description: 'terraform apply'
    required: false
    default: false
  status:
    description: 'terraform status'
    required: false
    default: false
  destroy:
    description: 'terraform destroy'
    required: false
    default: false
  custom_plan_flags:
    description: 'Add custom flags to the terraform plan command'
    required: false
    default: ''
  custom_apply_flags:
    description: 'Add custom flags to the terraform apply command'
    required: false
    default: ''
  github_pat:
    required: true
    
runs:
  using: "composite"
  steps:
    - run: |        
        wget https://github.com/im2nguyen/rover/releases/download/v0.3.3/rover_0.3.3_linux_amd64.zip
        unzip ./rover_0.3.3_linux_amd64.zip
        ls -l
        chmod +x ./rover_v0.3.3
        ./rover_v0.3.3 --help
      shell: bash

branding:
  icon: 'cloud'
  color: 'gray-dark'
