name: 'terraform_state_artifact'
description: 'Sets up and runs Terraform, and creates an encrypted Terraform artifact'
author: 'Sturla Bragason'
inputs:
  folder:
    description: folder
    required: false
    default: 'sandbox'
  branch_name:
    description: branch
    required: false
    default: 'main'
  encryptionkey:
    description: 'Used to read artifact and as a key to encrypt and decrypt the state file artifact'
    required: true
  apply:
    description: 'terraform apply'
    required: false
    default: false
  status:
    description: 'terraform status'
    required: false
    default: false
  destroy:
    description: 'terraform destroy'
    required: false
    default: false
  custom_plan_flags:
    description: 'Add custom flags to the terraform plan command'
    required: false
    default: ''
  custom_apply_flags:
    description: 'Add custom flags to the terraform apply command'
    required: false
    default: ''
  github_pat:
    required: true
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch_name }}
    - uses: hashicorp/setup-terraform@v2
    - id: terraform
      run: |
        cd ${{ inputs.folder }}
        wget https://github.com/im2nguyen/rover/releases/download/v0.3.3/rover_0.3.3_linux_amd64.zip
        unzip ./rover_0.3.3_linux_amd64.zip
        terraform init
        ls -l 
        ./rover_v0.3.3 --standalone
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.branch_name }}-${{ inputs.folder }}-rover"
        path: ./rover.zip

branding:
  icon: 'cloud'
  color: 'gray-dark'
