name: 'terraform_rover_artifact'
description: 'Sets up and runs Terraform, and creates an encrypted Terraform artifact'
author: 'Paul Kelleher'
inputs:
  folder:
    description: folder
    required: false
    default: 'sandbox'
  branch_name:
    description: branch
    required: false
    default: 'main'
  
    
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch_name }}
    - uses: hashicorp/setup-terraform@v2
    - id: terraform
      run: |
        cd ${{ inputs.folder }}
        wget https://github.com/im2nguyen/rover/releases/download/v0.3.3/rover_0.3.3_linux_amd64.zip
        unzip ./rover_0.3.3_linux_amd64.zip
        terraform init
        ls -l 
        ./rover_v0.3.3 --standalone
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: "${{ inputs.branch_name }}-${{ inputs.folder }}-rover.zip"
        path: ./${{ inputs.folder }}/rover.zip

branding:
  icon: 'cloud'
  color: 'gray-dark'
